In [1]:
# !nvidia-smi

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.0+cu116


In [3]:
# scalar = tf.constant(7) /// in tf

scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
# vector = tf.constant([10, 10])

vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [5]:
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
# matrix = tf.constant([[10, 7],
                    #   [7, 10]])

matrix = torch.tensor([[7, 8],
                      [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
matrix.ndim

2

In [9]:
matrix.shape

torch.Size([2, 2])

In [10]:
matrix[0]

tensor([7, 8])

In [11]:
matrix[0][0]

tensor(7)

In [12]:
matrix[1][0]

tensor(9)

In [13]:
TENSOR = torch.tensor([[[1,2,3],
                        [6,3,2],
                        [2,4,6]]])
TENSOR

tensor([[[1, 2, 3],
         [6, 3, 2],
         [2, 4, 6]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1982, 0.4254, 0.3779, 0.5579],
        [0.2139, 0.9714, 0.3978, 0.7920],
        [0.3460, 0.6560, 0.7796, 0.5386]])

In [17]:
random_tensor.ndim

2

In [18]:
random_tensor.shape

torch.Size([3, 4])

In [19]:
random_image_size_tensor = torch.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [22]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
ones.dtype

torch.float32

In [24]:
torch.range(0,10)

<ipython-input-24-dfdec9b83f7d>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,10)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [25]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
one_to_ten = torch.range(1, 11, 1)
one_to_ten

<ipython-input-26-f26c82ea7fc2>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  one_to_ten = torch.range(1, 11, 1)


tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [27]:
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [28]:
##############################

In [29]:
# Tensor Datatype

In [30]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,
                               device = None,
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [31]:
float_16_tensor = float_32_tensor.type(torch.half) ######## this works as well
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [32]:
new_tensor = float_32_tensor * float_16_tensor
new_tensor

tensor([ 9., 36., 81.])

In [33]:
new_tensor.dtype

torch.float32

In [34]:
import tensorflow as tf
tf_32 = tf.constant([3., 5.],
                    dtype=tf.float32)
tf_16 = tf.constant([5., 9.],
                    dtype=tf.float16)

In [35]:
tf_32

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 5.], dtype=float32)>

In [36]:
tf_16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([5., 9.], dtype=float16)>

In [37]:
# tf_16 * tf_32 ######## IN tf this will give error but it pyotch it did not, as we say

In [38]:
float_32_tensor.device

device(type='cpu')

In [39]:
###########################################

In [40]:
####### tensor operations

In [41]:
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [42]:
tensor * 10

tensor([10, 20, 30])

In [43]:
tensor - 10

tensor([-9, -8, -7])

In [44]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

In [45]:
######################################

In [46]:
####### Matrix multiplication

In [47]:
tensor * tensor

tensor([1, 4, 9])

In [48]:
torch.matmul(tensor, tensor)

tensor(14)

In [49]:
%%time
value = 0
for i in range(len(tensor)):
    value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.56 ms, sys: 116 µs, total: 2.67 ms
Wall time: 2.91 ms


In [50]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 1.97 ms, sys: 0 ns, total: 1.97 ms
Wall time: 1.79 ms


tensor(14)

In [51]:
 %%time
 tensor @ tensor

CPU times: user 2.69 ms, sys: 155 µs, total: 2.85 ms
Wall time: 3.12 ms


tensor(14)

In [52]:
###########################################

In [53]:
##### tensor aggregation ( min, max, mean, sum, etc)

In [54]:
x = torch.arange(0.0, 100.0, 10.0)
x

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [55]:
torch.min(x)

tensor(0.)

In [56]:
torch.max(x)

tensor(90.)

In [67]:
torch.mean(x), x.mean()

(tensor(45.), tensor(45.))

In [65]:
torch.sum(x), x.sum()

(tensor(450.), tensor(450.))

In [66]:
x.argmin(), torch.argmin(x)

(tensor(0), tensor(0))

In [60]:
x.argmax()

tensor(9)

In [61]:
y = torch.rand(10, dtype=torch.float32)
y

tensor([0.6418, 0.8460, 0.3610, 0.3762, 0.9889, 0.3245, 0.4071, 0.7799, 0.7321,
        0.1687])

In [62]:
y.argmax()

tensor(4)

In [63]:
#################################################

In [64]:
###### Reshaping, view, stacking, squeezing, unsqueezing, permute tensors

In [100]:
import torch
x = torch.arange(1.0, 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [101]:
x.size()

torch.Size([9])

In [102]:
x_reshaped = x.reshape(1,9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [103]:
x_reshaped1 = x.reshape(9,1)
x_reshaped1

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [104]:
z = x.view(1,9)
z

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [105]:
# z[:, 0] =5

In [106]:
z[0]

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [107]:
z[0][0]

tensor(1.)

In [108]:
xx = torch.arange(1.0, 31.)
xx
reshaped_3 = xx.reshape([2,5,3])
reshaped_3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.],
         [13., 14., 15.]],

        [[16., 17., 18.],
         [19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.],
         [28., 29., 30.]]])

In [109]:
reshaped_3[:, :, 1]

tensor([[ 2.,  5.,  8., 11., 14.],
        [17., 20., 23., 26., 29.]])

In [110]:
reshaped_3[1][0][1] = 71

In [111]:
reshaped_3

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.],
         [13., 14., 15.]],

        [[16., 71., 18.],
         [19., 20., 21.],
         [22., 23., 24.],
         [25., 26., 27.],
         [28., 29., 30.]]])

In [112]:
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [113]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [114]:
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [115]:
x_stacked2 = torch.stack([x,x,x,x], dim=1)
x_stacked2

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [116]:
# permute

In [127]:
x_original = torch.rand(size=(224,224,3))

In [129]:
x_original.shape

torch.Size([224, 224, 3])

In [122]:
x_permuted = x_original.permute(2,0,1)

In [130]:
x_permuted.shape

torch.Size([3, 224, 224])

In [131]:
#########################################################

In [132]:
###########Indexing

In [133]:
import torch
x = torch.arange(1, 10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [134]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [135]:
x[0][0]

tensor([1, 2, 3])

In [136]:
x[0][0][2]

tensor(3)

In [137]:
x[:]

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [138]:
x[:, 0]

tensor([[1, 2, 3]])

In [141]:
x[:, :, 0]

tensor([[1, 4, 7]])

In [144]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [143]:
x[:, 1, 1]

tensor([5])

In [145]:
x[0, 1, 1]

tensor(5)

In [146]:
###########################################

In [147]:
############ Pytorch from numpy torch.from_numpy

In [148]:
############### Pytorch to numpy torch.Tensor.numpy()

In [151]:
import torch
import numpy as np

array = np.arange(1.0, 8.0)

tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [152]:
array.dtype

dtype('float64')

In [153]:
tensor.dtype

torch.float64

In [155]:
torch.arange(1.0, 8.0).dtype


torch.float32

In [157]:
tensor = torch.ones(7)
tensor

tensor([1., 1., 1., 1., 1., 1., 1.])

In [158]:
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [159]:
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [160]:
#############################################

In [161]:
## Pytorch reproducibility 

In [162]:
import torch

random_tensor_A = torch.rand(3,4)
random_tensor_B = torch.rand(3,4)

random_tensor_A == random_tensor_B

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [163]:
#########################
# random seeds 

In [165]:
import torch

torch.manual_seed(42)

random_tensor_C = torch.rand(3,4)

torch.manual_seed(42)
random_tensor_D = torch.rand(3,4)

random_tensor_C == random_tensor_D

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [166]:
################### Ways to access GPU

In [1]:
!nvidia-smi

Tue Jan  3 13:00:11 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   66C    P0    27W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
torch.cuda.is_available()

True

In [3]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [4]:
torch.cuda.device_count()

1

In [5]:
############# PUtting tensors and models on the GPU

In [6]:
tensor = torch.tensor([1,2,3], device='cpu')
tensor.device


device(type='cpu')